import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'



export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Teste técnico Carol</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/brflogo.jpeg" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Boas vindas a <a href="https://www.brf-global.com/en/our-brands/">Lojinha da BRF!</a>
        </h1>

        <p className={styles.description}>
          Clique no produto desejado para ver o detalhamento!{' '}
          <code className={styles.code}></code>
        </p>


        <div className={styles.grid}>
          <a href="/product1" className={styles.card}>
            <h2>Produto 1 &rarr;</h2>
            <Image
    src="/images/almondega.jpg" // Route of the image file
    height={144} // Desired size with correct aspect ratio
    width={144} // Desired size with correct aspect ratio
    alt="Almondêga"
  />

            <p>Almondêga Veg e Tal.</p>
            <p>⭐⭐⭐⭐</p>
            <p>R$30,00</p>
          </a>
          <a href="/product1" className={styles.card}>
            <h2>Produto 1 &rarr;</h2>
            <Image
    src="/images/almondega.jpg" // Route of the image file
    height={144} // Desired size with correct aspect ratio
    width={144} // Desired size with correct aspect ratio
    alt="Almondêga"
  />

            <p>Almondêga Veg e Tal.</p>
            <p>⭐⭐⭐⭐</p>
            <p>R$30,00</p>
          </a>
          <a href="/product1" className={styles.card}>
            <h2>Produto 1 &rarr;</h2>
            <Image
    src="/images/almondega.jpg" // Route of the image file
    height={144} // Desired size with correct aspect ratio
    width={144} // Desired size with correct aspect ratio
    alt="Almondêga"
  />

            <p>Almondêga Veg e Tal.</p>
            <p>⭐⭐⭐⭐</p>
            <p>R$30,00</p>
          </a>
          <a href="/product1" className={styles.card}>
            <h2>Produto 1 &rarr;</h2>
            <Image
    src="/images/almondega.jpg" // Route of the image file
    height={144} // Desired size with correct aspect ratio
    width={144} // Desired size with correct aspect ratio
    alt="Almondêga"
  />

            <p>Almondêga Veg e Tal.</p>
            <p>⭐⭐⭐⭐</p>
            <p>R$30,00</p>
          </a>
          <a href="/product1" className={styles.card}>
            <h2>Produto 1 &rarr;</h2>
            <Image
    src="/images/almondega.jpg" // Route of the image file
    height={144} // Desired size with correct aspect ratio
    width={144} // Desired size with correct aspect ratio
    alt="Almondêga"
  />

            <p>Almondêga Veg e Tal.</p>
            <p>⭐⭐⭐⭐</p>
            <p>R$30,00</p>
          </a>
          <a href="/product1" className={styles.card}>
            <h2>Produto 1 &rarr;</h2>
            <Image
    src="/images/almondega.jpg" // Route of the image file
    height={144} // Desired size with correct aspect ratio
    width={144} // Desired size with correct aspect ratio
    alt="Almondêga"
  />

            <p>Almondêga Veg e Tal.</p>
            <p>⭐⭐⭐⭐</p>
            <p>R$30,00</p>
          </a>
          
         
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
